package generator

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// frameworkAbsPath returns the absolute path of the local go-yogan-framework
// checkout (sibling of the go-ygctl module root).
func frameworkAbsPath(t *testing.T) string {
	t.Helper()
	abs, err := filepath.Abs("../../../go-yogan-framework")
	if err != nil {
		t.Fatalf("resolve framework path: %v", err)
	}
	if _, err := os.Stat(abs); err != nil {
		t.Fatalf("framework path not found: %v", err)
	}
	return abs
}

// runGo executes a go command in dir and fails the test on error.
func runGo(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go %v failed in %s: %v\n%s", args, dir, err, out)
	}
}

// TestGeneratedAppsCompile is the compile gate: every app type generated by
// the templates must build and pass tests without manual fixes. This is the
// regression guard for "framework API changed but templates lagged behind".
func TestGeneratedAppsCompile(t *testing.T) {
	framework := frameworkAbsPath(t)
	org := "github.com/KOMKZ"

	cases := []struct {
		name    string
		project string
		app     string
		gen     func(project, app, module, output string) (string, error)
	}{
		{
			name:    "http",
			project: "gen-proj-http",
			app:     "demo-http",
			gen: func(project, app, module, output string) (string, error) {
				cfg := NewDefaultConfig()
				cfg.ProjectName, cfg.AppName, cfg.ModuleName = project, app, module
				cfg.OrgName = org
				cfg.OutputPath = output
				cfg.FrameworkPath = framework
				if err := NewHTTPGenerator(cfg).Generate(); err != nil {
					return "", err
				}
				return filepath.Join(output, project, "apps", app), nil
			},
		},
		{
			name:    "rpc",
			project: "gen-proj-rpc",
			app:     "demo-rpc",
			gen: func(project, app, module, output string) (string, error) {
				cfg := NewDefaultRPCConfig()
				cfg.ProjectName, cfg.AppName, cfg.ModuleName = project, app, module
				cfg.OrgName = org
				cfg.OutputPath = output
				cfg.FrameworkPath = framework
				cfg.ServiceName = "Demo"
				if err := NewRPCGenerator(cfg).Generate(); err != nil {
					return "", err
				}
				return filepath.Join(output, project, "apps", app), nil
			},
		},
		{
			name:    "cli",
			project: "gen-proj-cli",
			app:     "demo-cli",
			gen: func(project, app, module, output string) (string, error) {
				cfg := NewDefaultCLIConfig()
				cfg.ProjectName, cfg.AppName, cfg.ModuleName = project, app, module
				cfg.OrgName = org
				cfg.OutputPath = output
				cfg.FrameworkPath = framework
				if err := NewCLIGenerator(cfg).Generate(); err != nil {
					return "", err
				}
				return filepath.Join(output, project, "apps", app), nil
			},
		},
		{
			name:    "cron",
			project: "gen-proj-cron",
			app:     "demo-cron",
			gen: func(project, app, module, output string) (string, error) {
				cfg := NewDefaultCronConfig()
				cfg.ProjectName, cfg.AppName, cfg.ModuleName = project, app, module
				cfg.OrgName = org
				cfg.OutputPath = output
				cfg.FrameworkPath = framework
				if err := NewCronGenerator(cfg).Generate(); err != nil {
					return "", err
				}
				return filepath.Join(output, project, "apps", app), nil
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			output := t.TempDir()
			module := fmt.Sprintf("%s/%s/apps/%s", org, tc.project, tc.app)

			appDir, err := tc.gen(tc.project, tc.app, module, output)
			if err != nil {
				t.Fatalf("generate failed: %v", err)
			}

			// go.work lives at the project root; commands run in the app dir
			// resolve it upward.
			runGo(t, appDir, "mod", "tidy")
			runGo(t, appDir, "build", "./...")
			runGo(t, appDir, "test", "./...")

			// The shared pkg module must compile as well (errdef/apputil).
			pkgDir := filepath.Join(filepath.Dir(appDir), "..", "pkg")
			runGo(t, pkgDir, "build", "./...")
		})
	}
}

// TestGeneratedHTTPBuildScript verifies that scripts/build.sh injects
// version/build-time/commit into the binary (-X against a const fails
// silently — this is the regression guard for that).
func TestGeneratedHTTPBuildScript(t *testing.T) {
	framework := frameworkAbsPath(t)
	output := t.TempDir()

	cfg := NewDefaultConfig()
	cfg.ProjectName, cfg.AppName = "gen-proj-build", "demo-http"
	cfg.ModuleName = "github.com/KOMKZ/gen-proj-build/apps/demo-http"
	cfg.OrgName = "github.com/KOMKZ"
	cfg.OutputPath = output
	cfg.FrameworkPath = framework
	if err := NewHTTPGenerator(cfg).Generate(); err != nil {
		t.Fatalf("generate failed: %v", err)
	}

	appDir := filepath.Join(output, cfg.ProjectName, "apps", cfg.AppName)
	runGo(t, appDir, "mod", "tidy")

	cmd := exec.Command(filepath.Join(appDir, "scripts", "build.sh"))
	cmd.Dir = appDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build.sh failed: %v\n%s", err, out)
	}

	binary := filepath.Join(appDir, "build", cfg.AppName)
	verCmd := exec.Command("go", "version", "-m", binary)
	verOut, err := verCmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go version -m failed: %v\n%s", err, verOut)
	}
	for _, want := range []string{"main.Version", "main.BuildTime", "main.GitCommit"} {
		if !strings.Contains(string(verOut), want) {
			t.Fatalf("build settings missing %s:\n%s", want, verOut)
		}
	}
}

// TestGeneratedHTTPRestartScript verifies that scripts/restart.sh rebuilds
// before restarting so generated apps do not keep running stale binaries.
func TestGeneratedHTTPRestartScript(t *testing.T) {
	framework := frameworkAbsPath(t)
	output := t.TempDir()

	cfg := NewDefaultConfig()
	cfg.ProjectName, cfg.AppName = "gen-proj-restart", "demo-http"
	cfg.ModuleName = "github.com/KOMKZ/gen-proj-restart/apps/demo-http"
	cfg.OrgName = "github.com/KOMKZ"
	cfg.OutputPath = output
	cfg.FrameworkPath = framework
	if err := NewHTTPGenerator(cfg).Generate(); err != nil {
		t.Fatalf("generate failed: %v", err)
	}

	appDir := filepath.Join(output, cfg.ProjectName, "apps", cfg.AppName)
	restartPath := filepath.Join(appDir, "scripts", "restart.sh")
	content, err := os.ReadFile(restartPath)
	if err != nil {
		t.Fatalf("read restart script failed: %v", err)
	}
	text := string(content)
	for _, want := range []string{
		"# 重启 demo-http 应用（先编译，再停止旧进程并启动）",
		`"$SCRIPT_DIR/start.sh" -d -b -f "$@"`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("restart script missing %q:\n%s", want, text)
		}
	}
}
