package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestListDefFiles_SkipsUIDefsAndSorts(t *testing.T) {
	dir := t.TempDir()
	defsDir := filepath.Join(dir, "defs")
	if err := os.MkdirAll(defsDir, 0755); err != nil {
		t.Fatalf("mkdir defs: %v", err)
	}

	files := map[string]string{
		"zeta.yaml":     "domain: zeta\nentity: zeta\ntable: zetas\nfields:\n  - {name: name, type: string}\n",
		"admin.ui.yaml": "menu:\n  title: Admin\n",
		"alpha.yaml":    "domain: alpha\nentity: alpha\ntable: alphas\nfields:\n  - {name: name, type: string}\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(defsDir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	got, err := ListDefFiles(dir)
	if err != nil {
		t.Fatalf("ListDefFiles() err = %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("len(got) = %d, want 2", len(got))
	}
	if filepath.Base(got[0]) != "alpha.yaml" || filepath.Base(got[1]) != "zeta.yaml" {
		t.Fatalf("unexpected order: %#v", got)
	}
}

func TestLoadDef_NormalizesCustomRouteBaseAndEndpointPaths(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "storage.yaml")
	content := `
domain: storage
entity: file
table: storage_files
route_base: files
fields:
  - {name: storage_id, type: string, size: 500, required: true}
endpoints:
  - {action: list, method: get, path: .}
  - {action: create, method: post, path: upload}
  - {action: delete}
`
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write def: %v", err)
	}

	def, err := LoadDef(path)
	if err != nil {
		t.Fatalf("LoadDef() err = %v", err)
	}
	if def.RouteBase != "/files" {
		t.Fatalf("route_base = %q, want /files", def.RouteBase)
	}
	if def.Endpoints[0].Method != "GET" || def.Endpoints[0].RoutePath != "" {
		t.Fatalf("list route = %s %q, want GET empty", def.Endpoints[0].Method, def.Endpoints[0].RoutePath)
	}
	if def.Endpoints[1].Method != "POST" || def.Endpoints[1].RoutePath != "/upload" {
		t.Fatalf("create route = %s %q, want POST /upload", def.Endpoints[1].Method, def.Endpoints[1].RoutePath)
	}
	if def.Endpoints[2].Method != "DELETE" || def.Endpoints[2].RoutePath != "/:id" {
		t.Fatalf("delete route = %s %q, want DELETE /:id", def.Endpoints[2].Method, def.Endpoints[2].RoutePath)
	}
}

func TestFieldStructTag_IncludesNonUniqueIndex(t *testing.T) {
	got := FieldStructTag(DefField{Name: "storage", Type: "string", Size: 50, Index: true})
	if !strings.Contains(got, `gorm:"index;size:50"`) {
		t.Fatalf("FieldStructTag() = %q, want indexed gorm tag", got)
	}
}

func TestGeneratePermissionDeclarations_RegeneratesExistingFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "defs", "permissions"), 0755); err != nil {
		t.Fatalf("mkdir permission defs: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.work"), []byte("go 1.24.1\n"), 0644); err != nil {
		t.Fatalf("write go.work: %v", err)
	}
	appDir := filepath.Join(dir, "apps", "hrise-admin-api")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("mkdir app: %v", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, "go.mod"), []byte("module github.com/KOMKZ/hrise-server-app/apps/hrise-admin-api\n"), 0644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	defContent := `
domain: admin
permissions:
  - code: admin:read
    name: View admins
    type: read
    group: SYSTEM
    apis:
      - {method: get, path: /api/admins/page}
`
	if err := os.WriteFile(filepath.Join(dir, "defs", "permissions", "admin.yaml"), []byte(defContent), 0644); err != nil {
		t.Fatalf("write permission def: %v", err)
	}

	outPath := filepath.Join(dir, "domains", "admin", "permissions", "declared_permissions.go")
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		t.Fatalf("mkdir permissions: %v", err)
	}
	original := []byte("package permissions\n\nvar Stale = true\n")
	if err := os.WriteFile(outPath, original, 0644); err != nil {
		t.Fatalf("write existing file: %v", err)
	}

	warnings, err := GeneratePermissionDeclarations(dir, "admin", apiTemplates, "templates/api")
	if err != nil {
		t.Fatalf("GeneratePermissionDeclarations() err = %v", err)
	}
	if len(warnings) != 0 {
		t.Fatalf("warnings len = %d, want 0", len(warnings))
	}
	got, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	text := string(got)
	if text == string(original) {
		t.Fatalf("existing file was not regenerated")
	}
	if !strings.Contains(text, "Code generated by ygctl from defs/permissions/*.yaml; DO NOT EDIT.") {
		t.Fatalf("missing generated header: %q", text)
	}
	if !strings.Contains(text, `PermissionCode: "admin:read"`) {
		t.Fatalf("missing generated permission: %q", text)
	}
}

func TestGenerateAllPermissionDeclarations_RegeneratesPurePermissionDomain(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "defs", "permissions"), 0755); err != nil {
		t.Fatalf("mkdir permission defs: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.work"), []byte("go 1.24.1\n"), 0644); err != nil {
		t.Fatalf("write go.work: %v", err)
	}
	appDir := filepath.Join(dir, "apps", "hrise-admin-api")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("mkdir app: %v", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, "go.mod"), []byte("module github.com/KOMKZ/hrise-server-app/apps/hrise-admin-api\n"), 0644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	defContent := `
domain: rbac
permissions:
  - code: role:read
    name: View roles
    type: read
    apis:
      - {method: get, path: /api/roles/page}
`
	if err := os.WriteFile(filepath.Join(dir, "defs", "permissions", "rbac.yaml"), []byte(defContent), 0644); err != nil {
		t.Fatalf("write permission def: %v", err)
	}

	outPath := filepath.Join(dir, "domains", "rbac", "permissions", "declared_permissions.go")
	if _, err := GenerateAllPermissionDeclarations(dir, apiTemplates, "templates/api"); err != nil {
		t.Fatalf("GenerateAllPermissionDeclarations() err = %v", err)
	}
	got, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	text := string(got)
	if !strings.Contains(text, `PermissionCode: "role:read"`) {
		t.Fatalf("missing rbac permission: %q", text)
	}
	if !strings.Contains(text, `PathPattern:    "/api/roles/page"`) {
		t.Fatalf("missing rbac policy: %q", text)
	}
}

func TestSyncPermissionDeclaration_MissingDomain(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "defs", "permissions"), 0755); err != nil {
		t.Fatalf("mkdir permission defs: %v", err)
	}
	err := SyncPermissionDeclaration(dir, "rbac")
	if err == nil {
		t.Fatal("expected missing domain error")
	}
	if !strings.Contains(err.Error(), `permission DSL for domain "rbac" not found`) {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBuildDeclaredPermissionData_EmitsAPIPolicies(t *testing.T) {
	data := buildDeclaredPermissionData("github.com/KOMKZ/hrise-server-app", PermissionDef{
		Domain: "admin",
		Permissions: []PermissionDefItem{
			{
				Code:  "admin:read",
				Name:  "View admins",
				Type:  "READ",
				Group: "SYSTEM",
				APIs: []PermissionAPI{
					{Method: "GET", Path: "/api/admins/page"},
				},
			},
		},
	})
	if len(data.Permissions) != 1 {
		t.Fatalf("permissions len = %d, want 1", len(data.Permissions))
	}
	if len(data.Policies) != 1 {
		t.Fatalf("policies len = %d, want 1", len(data.Policies))
	}
	if data.Policies[0].Path != "/api/admins/page" {
		t.Fatalf("policy path = %q, want api path", data.Policies[0].Path)
	}
}
